version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project
    steps:
      - checkout:
          name: main
          path: ~/project
      - run: npm install
workflows:
  deploy:
    jobs:
      - deploy
