version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    working_directory: ~/project
    executor: node/default
    steps:
      - checkout:
          name: main
          path: ~/project
      - run: npm install
workflows:
  deploy:
    jobs:
      - deploy
